//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MegaPhone.DataFolder
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tasks
    {
        public int id { get; set; }
        public int user_id { get; set; }
        public Nullable<int> category_id { get; set; }
        public System.DateTime date { get; set; }
        public string description { get; set; }
    
        public virtual Categories Categories { get; set; }
        public virtual Users Users { get; set; }
    }
}
